# Generated by Django 5.1.4 on 2025-01-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_rename_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='systemapp.menuitem'),
        ),
    ]
