# Generated by Django 5.2.5 on 2025-08-16 12:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='images'),
        ),
    ]
